spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/spring-boot-gda?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false

    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 20
    minIdle: 25
    maxActive: 100

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


server:
  servlet:
    context-path: /gda
  port: 8088